kafka:
  pool: nav-prod
cluster: prod-gcp
urlPdl: pdl-api.prod-fss-pub.nais.io
endpoints:
  pdl: https://pdl-api.prod-fss-pub.nais.io/graphql
audience:
  pdl: prod-fss:pdl:pdl-api
scope:
  pdl: api://prod-fss.pdl.pdl-api/.default
